/**
 * This file was generated automatically by Supernova.io and should not be changed manually.
 * To modify the format or content of this file, please contact your design system team. 
 */

const componentColorsLight = {
  global: {
    "selected": "#3177ff33",
    "segmentControlBg": "#eaecf2",
    "notificationDot": "#f5403e",
    "mobileBackground": "#f1f3f7",
    "webNavBarBackground": "#010f31",
  },
  calendar: {
    "structureBlockGeneric": "#3d599954",
    "defaultBackground": "#ffffff",
    "workoutCardBg": "#ffffff",
    "weekHeaderBackground": "#ffffff",
    "weekHeaderCurrentBackground": "#dce0e8",
    "todayHeaderBackground": "#1840ec",
    "unplannedStructureBlockGeneric": "#c3c9d7",
    "dayTSSBackground": "#dce0e8",
    "availabilityDayBackground": "#f1f3f7",
    "groupAthleteBackground": "#f1f3f7",
    "unavailable": "#cc3634",
    "unavailableBg": "#fcc2c1",
    "unavailableContrastText": "#7d2120",
    "limitedAvailability": "#ffaa02",
    "limitedAvailabilityBg": "#fffcee",
    "limitedAvailabilityContrastText": "#5a3c01",
    "structureBlockCompletedGeneric": "#414e6c",
  },
  graph: {
    "runGraphBg": "#006277b2",
    "hrFaded": "#fea0cb80",
    "structureBarBase": "#1840ec80",
    "structureBarRange": "#1840ec4d",
    "graphArea": "#cfd8e399",
    "totalDuration": "#1840ec",
    "totalTSS": "#1840ec",
    "totalTSSPlannedBackground": "#98bbff",
    "totalDurationPlannedBackground": "#98bbff",
    "graphBackground": "#f1f3f7",
    "elvationBackground": "#acb4c7",
    "axisLabel": "#414e6c",
    "StackUpYou": "#1840ec",
    "StackUpOthers": "#c3c9d7",
    "graphOther": "#c3c9d7",
    "temperature": "#98bbff",
    "temperatureFaded": "#aec5f180",
    "pace": "#4370f6",
    "paceFaded": "#98b8f680",
    "power": "#b63fee",
    "powerFaded": "#d783ff80",
    "hr": "#e05193",
    "cadence": "#fe9301",
    "cadenceFaded": "#ffe1b280",
    "graphDivider": "#f1f3f7",
    "graphAxis": "#c3c9d7",
    "graphCalorieConsumed": "#5fc200",
    "graphCalorieExpended": "#acb4c7",
    "graphMacroCarb": "#259500",
    "graphMacroFat": "#5fc200",
    "graphMacroProtein": "#99d85d",
    "graphMacroExpended": "#aec5f1",
    "graphMacroConsumed": "#aec5f1",
    "graphTSS": "#a52c2a",
    "work": "#5e1680",
    "variabilityIndex": "#5e1680",
    "graphIntensityFactor": "#3177ff",
    "graphDistance": "#1840ec",
    "graphKj": "#3177ff",
    "weeklySummaryBarGraphBG": "#eaecf2",
    "weeklySummaryBarGraphOverBG": "#939db6",
    "common": "#1840ec",
    "graphBase": "#dce0e8",
    "graphUnder": "#acb4c7",
    "graphOver": "#414e6c",
    "metricPrimary": "#6c9eff",
    "metricSecondary": "#fec42e",
    "metricTertiary": "#f5403e",
    "graphBar": "#acb4c7",
    "graphBarActive": "#6a758f",
  },
  input: {
    "border": "#1a202e3b",
  },
  chat: {
    "rightbubbleBackground": "#3177ff",
    "leftbubbleBackground": "#f1f3f7",
    "typingindicatorBackground": "#f1f3f7",
    "border": "#aec5f1",
    "backgroundNotCurrentUser": "#f1f3f7",
  },
  map: {
    "path": "#0d2994",
    "start": "#259500",
    "end": "#7d2120",
    "markerBackground": "#f1f3f7",
  },
  atp: {
    "graphBg1": "#f1f3f7",
    "graphBg2": "#dce0e8",
    "base1": "#939db6",
    "base2": "#6a758f",
    "base3": "#414e6c",
    "build1": "#99d85d",
    "build2": "#5fc200",
    "race": "#1840ec",
    "transition": "#bdbdbd",
    "peak": "#ffaa02",
    "preperation": "#757575",
  },
  premiumTag: {
    "background": "#d6e4ff",
    "text": "#1840ec",
  },
  tpds-chip: {
    "default-subtle-fg": "#414e6c",
    "default-subtle-bg": "#dce0e8",
    "primary-subtle-fg": "#061a5a",
    "primary-subtle-bg": "#d6e4ff",
    "secondary-subtle-fg": "#57062a",
    "secondary-subtle-bg": "#fce4ef",
    "success-subtle-fg": "#1a6800",
    "success-subtle-bg": "#eff6e9",
    "warning-subtle-fg": "#8b5d01",
    "warning-subtle-bg": "#fffcee",
    "error-subtle-fg": "#641b1a",
    "error-subtle-bg": "#feebeb",
  }
};

export default componentColorsLight;