/**
 * This file was generated automatically by Supernova.io and should not be changed manually.
 * To modify the format or content of this file, please contact your design system team. 
 */

const componentColorsDark = {
  global: {
    "selected": "#3177ff33",
    "segmentControlBg": "#1a202e",
    "notificationDot": "#cc3634",
    "mobileBackground": "#1f2633",
    "webNavBarBackground": "#010f31",
  },
  calendar: {
    "structureBlockGeneric": "#acb4c754",
    "structureBlockCompletedGeneric": "#fbfcfe54",
    "defaultBackground": "#0d0f17",
    "workoutCardBg": "#141823",
    "weekHeaderBackground": "#0d0f17",
    "weekHeaderCurrentBackground": "#1a202e",
    "todayHeaderBackground": "#3177ff",
    "unplannedStructureBlockGeneric": "#414e6c",
    "dayTSSBackground": "#414e6c",
    "availabilityDayBackground": "#1a202e",
    "groupAthleteBackground": "#414e6c",
    "unavailable": "#cc3634",
    "unavailableBg": "#641b1a",
    "unavailableContrastText": "#fcc2c1",
    "limitedAvailability": "#ffaa02",
    "limitedAvailabilityBg": "#8b5d01",
    "limitedAvailabilityContrastText": "#ffe892",
  },
  graph: {
    "runGraphBg": "#ffffff",
    "structureBarBase": "#1840ec80",
    "structureBarRange": "#1840ec4d",
    "graphArea": "#6f7b964d",
    "hrFaded": "#a0346680",
    "totalDuration": "#1840ec",
    "totalTSS": "#1840ec",
    "totalTSSPlannedBackground": "#98bbff",
    "totalDurationPlannedBackground": "#98bbff",
    "graphBackground": "#1a202e",
    "elvationBackground": "#6a758f",
    "axisLabel": "#eaecf2",
    "StackUpYou": "#3177ff",
    "StackUpOthers": "#414e6c",
    "graphOther": "#414e6c",
    "temperature": "#98bbff",
    "temperatureFaded": "#0d299480",
    "pace": "#4370f6",
    "paceFaded": "#1336c380",
    "power": "#b63fee",
    "powerFaded": "#8323b080",
    "hr": "#e05193",
    "cadence": "#fe9301",
    "cadenceFaded": "#ac470180",
    "graphDivider": "#414e6c",
    "graphAxis": "#414e6c",
    "graphCalorieConsumed": "#5fc200",
    "graphCalorieExpended": "#acb4c7",
    "graphMacroCarb": "#259500",
    "graphMacroFat": "#5fc200",
    "graphMacroProtein": "#99d85d",
    "graphMacroExpended": "#aec5f1",
    "graphMacroConsumed": "#aec5f1",
    "graphTSS": "#f5403e",
    "work": "#5e1680",
    "variabilityIndex": "#5e1680",
    "graphIntensityFactor": "#3177ff",
    "graphDistance": "#1840ec",
    "graphKj": "#6c9eff",
    "weeklySummaryBarGraphBG": "#1a202e",
    "weeklySummaryBarGraphOverBG": "#1a202e",
    "common": "#3177ff",
    "graphBase": "#6a758f",
    "graphUnder": "#6a758f",
    "graphOver": "#414e6c",
    "metricPrimary": "#6c9eff",
    "metricSecondary": "#b97c01",
    "metricTertiary": "#7d2120",
    "graphBar": "#414e6c",
    "graphBarActive": "#6a758f",
  },
  input: {
    "border": "#ffffff",
  },
  atp: {
    "base1": "#ffffff",
    "base2": "#ffffff",
    "base3": "#ffffff",
    "build1": "#ffffff",
    "build2": "#ffffff",
    "race": "#ffffff",
    "transition": "#ffffff",
    "peak": "#ffffff",
    "preperation": "#ffffff",
    "graphBg1": "#1a202e",
    "graphBg2": "#414e6c",
  },
  chat: {
    "rightbubbleBackground": "#aec5f1",
    "leftbubbleBackground": "#6a758f",
    "typingindicatorBackground": "#6a758f",
    "border": "#aec5f1",
    "backgroundNotCurrentUser": "#f1f3f7",
  },
  map: {
    "path": "#3177ff",
    "start": "#78cb28",
    "end": "#f5403e",
    "markerBackground": "#414e6c",
  },
  premiumTag: {
    "background": "#061a5a",
    "text": "#3177ff",
  },
  tpds-chip: {
    "default-subtle-fg": "#414e6c",
    "default-subtle-bg": "#eaecf2",
    "primary-subtle-fg": "#061a5a",
    "primary-subtle-bg": "#98bbff",
    "secondary-subtle-fg": "#57062a",
    "secondary-subtle-bg": "#fe98c7",
    "success-subtle-fg": "#1a6800",
    "success-subtle-bg": "#afe080",
    "warning-subtle-fg": "#5a3c01",
    "warning-subtle-bg": "#ffd55b",
    "error-subtle-fg": "#641b1a",
    "error-subtle-bg": "#fa9594",
  }
};

export default componentColorsDark;